export const SITE = {
  title: '编程内外',
  description: '记录学习，也记录上下求索的过程。',
  repository: 'https://github.com/CELFS/Notes',
  logoAlt: '编程内外 Logo',
  homeLabel: '首页',
  navigationLabel: '笔记目录',
  searchLabel: '搜索笔记',
  searchShortcut: '⌘ K',
  searchPlaceholder: '输入标题、目录或正文关键词',
  searchEmpty: '没有找到匹配的笔记',
  searchInitial: '输入关键词开始搜索',
  closeSearch: '关闭搜索',
  repositoryLabel: '查看 GitHub 仓库',
  switchToLight: '切换到亮色模式',
  switchToDark: '切换到暗色模式',
  openNavigation: '打开笔记目录',
  closeNavigation: '关闭笔记目录',
  contentsLabel: '本页目录',
  expandContents: '展开本页目录',
  collapseContents: '收起本页目录',
  scrollToTop: '滚动到顶部',
  documentPathLabel: '文档路径',
  subdirectoriesLabel: '子目录',
  documentsLabel: '笔记',
  emptyDirectoryLabel: '这个目录暂时没有可公开的内容。',
  wordCountLabel: '字',
  updatedAtLabel: '更新于',
  adjacentNotesLabel: '相邻笔记',
  copyCodeLabel: '复制代码',
  copiedCodeLabel: '已复制',
  previousLabel: '上一篇',
  nextLabel: '下一篇',
  imageViewerLabel: '图片查看器',
  openImageViewer: '查看大图',
  closeImageViewer: '关闭图片查看器',
  previousImage: '上一张图片',
  nextImage: '下一张图片',
  zoomInImage: '放大图片',
  zoomOutImage: '缩小图片',
  resetImageZoom: '重置图片缩放',
  emptyTitle: '发布目录还是空的',
  emptyDescription: '把确认公开的 Markdown 原文件复制到 src/content/notes 后，目录和页面会自动生成。',
} as const;
